# Generated by Django 3.2.18 on 2023-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage Anniversary', 'Marriage Anniversary'), ('Work Anniversary', 'Work Anniversary')], max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
