# Generated by Django 3.2.18 on 2023-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage Anniversary', 'Marriage Anniversary'), ('Work Anniversary', 'Work Anniversary')], max_length=50, unique=True),
        ),
    ]
